-- Your SQL goes here
ALTER TABLE emails ADD COLUMN num_sent INTEGER NOT NULL DEFAULT 0;
ALTER TABLE emails ADD COLUMN num_opened INTEGER NOT NULL DEFAULT 0;
ALTER TABLE emails ADD COLUMN num_replied INTEGER NOT NULL DEFAULT 0;
