-- Your SQL goes here
CREATE TABLE IF NOT EXISTS emails (
    id INTEGER NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_recipients (
    id INTEGER NOT NULL PRIMARY KEY,
    email_id INTEGER NOT NULL REFERENCES emails(id),
    address VARCHAR(255) NOT NULL,
    opened BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
