name: Deploy development

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CICD_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.CICD_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Deploy
        run: |
          scp ./target/release/pushkind-emailer cicd@admin.pushkind.com:/var/www5/html/
          scp ./assets/* cicd@admin.pushkind.com:/var/www5/html/assets/
          scp ./templates/* cicd@admin.pushkind.com:/var/www5/html/assets/
